version: '3'
name: 'uts-4-project'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: project
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.docker/minio:/data
    command: server --console-address ":9001" /data
