version: '3'
name: 'uts-4-project'

services:
  mysql:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: project
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: 'mysqld --max-connections=1000'
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.docker/minio:/data
    command: server --console-address ":9001" /data
